### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by dingxusen** [endogslam/EndoGSLAM#2]
Evaluating Final Parameters ...
100%|██████████████████████████████████████| 613/613 [00:00<00:00, 28937.95it/s]
  1%|▍                                          | 7/613 [00:00<00:07, 82.16it/s]
Traceback (most recent call last):
  File "/home/ail606/EndoGSLAM/scripts/main.py", line 971, in <module>
    rgbd_slam(experiment.config)
  File "/home/ail606/EndoGSLAM/scripts/main.py", line 922, in rgbd_slam
    eval_save(dataset, params, eval_dir, sil_thres=config['mapping']['sil_thres'],
  File "/home/ail606/EndoGSLAM/utils/eval_helpers.py", line 390, in eval_save
    cv2.imwrite(os.path.join(render_rgb_dir, "color_{:04d}.png".format(total_time_idx)), cv2.cvtColor(save_im, cv2.COLOR_RGB2BGR))
cv2.error: OpenCV(4.10.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src'

![2024-06-26 14-21-45屏幕截图](https://github.com/Loping151/EndoGSLAM/assets/44423814/7a4bc144-5e76-48f5-81fb-9d3471f18508)

Excuse me, how should this problem be solved? I look forward to your reply

**Comment by Loping151** [comment]
It seems an opencv package error. Try
`pip install opencv-python==4.9` to downgrade.

**Comment by dingxusen** [comment]
> 似乎是 opencv 包错误。尝试 `pip install opencv-python==4.9`降级。

100%|███████████████████████████████████████████| 613/613 [00:00<00:00, 29400.90it/s]
  1%|▌                                               | 7/613 [00:00<00:25, 23.32it/s]
Traceback (most recent call last):
  File "/home/ail606/EndoGSLAM/scripts/main.py", line 971, in <module>
    rgbd_slam(experiment.config)
  File "/home/ail606/EndoGSLAM/scripts/main.py", line 922, in rgbd_slam
    eval_save(dataset, params, eval_dir, sil_thres=config['mapping']['sil_thres'],
  File "/home/ail606/EndoGSLAM/utils/eval_helpers.py", line 400, in eval_save
    plot_rgbd_silhouette(color, depth, im, rastered_depth_viz, presence_sil_mask, diff_depth_l1,
  File "/home/ail606/EndoGSLAM/utils/eval_helpers.py", line 118, in plot_rgbd_silhouette
    plt.savefig(save_path, bbox_inches='tight')
  File "/home/ail606/miniconda3/envs/endogslam1/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1223, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/home/ail606/miniconda3/envs/endogslam1/lib/python3.10/site-packages/matplotlib/figure.py", line 3388, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/ail606/miniconda3/envs/endogslam1/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2218, in print_figure
    result = print_method(
  File "/home/ail606/miniconda3/envs/endogslam1/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2068, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/home/ail606/miniconda3/envs/endogslam1/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 496, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/home/ail606/miniconda3/envs/endogslam1/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 444, in _print_pil
    FigureCanvasAgg.draw(self)
  File "/home/ail606/miniconda3/envs/endogslam1/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 387, in draw
    self.figure.draw(self.renderer)
  File "/home/ail606/miniconda3/envs/endogslam1/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/home/ail606/miniconda3/envs/endogslam1/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/ail606/miniconda3/envs/endogslam1/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    self.patch.draw(renderer)
  File "/home/ail606/miniconda3/envs/endogslam1/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/ail606/miniconda3/envs/endogslam1/lib/python3.10/site-packages/matplotlib/patches.py", line 632, in draw
    self._draw_paths_with_artist_properties(
  File "/home/ail606/miniconda3/envs/endogslam1/lib/python3.10/site-packages/matplotlib/patches.py", line 617, in _draw_paths_with_artist_properties
    renderer.draw_path(gc, *draw_path_args)
  File "/home/ail606/miniconda3/envs/endogslam1/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 131, in draw_path
    self._renderer.draw_path(gc, path, transform, rgbFace)
ValueError: object __array__ method not producing an array
(endogslam1) ail606@ail606:~/EndoGSLAM$ 
![image](https://github.com/Loping151/EndoGSLAM/assets/44423814/c77dc46e-f04e-44b5-9166-be7e0d8ed6a8)

These errors occurred after downgrading. In the preprocessed data you provided, three images of the sigmoid_t3_a data were damaged, namely 0198_color.png, 0396_color.png, and 0404_color.png. I replaced them with their respective previous images after renaming. Not only this dataset, but other files also have a small number of damaged images after decompression. The first question I raised was also based on training after replacing damaged images.

**Comment by Loping151** [comment]
I'm sorry for the dataset. I'll check the compressed file before Sunday. But for the error you mention, it is likely because PILLOW was downgraded with opencv and the replaced version fails to work well with matplotlib. I think you can first try to reinstall matplotlib. 

For the data, I'll let you know when I've checked.

**Comment by Rashfu** [comment]
Apart from the previous problems, another tip is here:
The command `pip install torch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu118` automatically installs the numpy2.0, which is not compatible with the code(Ubuntu22.0+RTX3090). So, specifying numpy==1.26 will fix the problem.

Also waiting for the new data.

**Comment by dingxusen** [comment]
> I'm sorry for the dataset. I'll check the compressed file before Sunday. But for the error you mention, it is likely because PILLOW was downgraded with opencv and the replaced version fails to work well with matplotlib. I think you can first try to reinstall matplotlib.
> 
> For the data, I'll let you know when I've checked.
Thank you for your answer, I succeeded in running it!

**Comment by dingxusen** [comment]
> Apart from the previous problems, another tip is here: The command `pip install torch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu118` automatically installs the numpy2.0, which is not compatible with the code(Ubuntu22.0+RTX3090). So, specifying numpy==1.26 will fix the problem.
> 
> Also waiting for the new data.

Yes, I encountered this problem as well.

**Comment by Loping151** [comment]
Hello,

I've updated requirements.txt to prevent environment issues. I've made new compressed files and checked the data.

**Comment by dingxusen** [comment]
> 你好，
> 
> 我已经更新了 requirements.txt 以防止出现环境问题。我制作了新的压缩文件并检查了数据。

Thank you very much!
